#!/bin/bash
# Copyright (C) 2009 Andrea Francia Trivolzio(PV) Italy
# Licensed under the GNU General Public License

source "$(dirname $0)"/svn-ignore.bash
source svn-ignore-tests.bash
source bashunit.bash
