#!/bin/bash


function svn-add-to-ignore-list () {
  local path_to_ignore="$1"
  concat-to-current-ignore-list "$path_to_ignore" | svn propset svn:ignore -F- . >/dev/null
}

function concat-to-current-ignore-list() {
  concat-to-current-ignore-list-with-annoying-blank-line "$1" | discard-empty-lines
}

function concat-to-current-ignore-list-with-annoying-blank-line() {
  local new_path_to_ignore="$1"
  svn-get-ignore-list
  echo "$new_path_to_ignore"
}


function svn-get-ignore-list() {
  local wc_path="${1:-"."}"
  svn propget svn:ignore "$wc_path"
}

function discard-empty-lines() {
  sed '/^\s*$/d'
}

function test-add-first-ignore() {
  setup-test-repo-and-wc
  
  (
    cd wc
    svn-add-to-ignore-list path-to-ignore
  )
  
  assertEquals "path-to-ignore" "$(read-ignore-prop wc)"
}

function test-append-second-ignore() {
  setup-test-repo-and-wc
  
  (
    cd wc
    svn-add-to-ignore-list first-path-to-ignore
    svn-add-to-ignore-list second-path-to-ignore
  )
  
  assertEquals "first-path-to-ignore
second-path-to-ignore" "$(read-ignore-prop wc)"
}


function test-get-current-ignore-list() {
  setup-test-repo-and-wc
  (
    cd wc
    svn-add-to-ignore-list my-path-to-ignore
  )
  
  assertEquals "my-path-to-ignore" "$(svn-get-ignore-list wc)"
}


function test-that-repo-is-clean() {
  setup-test-repo-and-wc

  local ignore="$(read-ignore-prop wc)"
  
  assertEquals "" "$ignore"
}




function read-ignore-prop() {
  local wc="$1"
  svn propget svn:ignore "$wc"
}


function setup-test-repo-and-wc() {
  rm -Rf repo
  rm -Rf wc
  svnadmin create repo >/dev/null
  svn co file://$(pwd)/repo wc >/dev/null
}

source bashunit.bash