#!/bin/bash
# Copyright (C) 2009 Andrea Francia Trivolzio(PV) Italy
# Licensed under the GNU General Public License

user_message="${1:-""}"
test_results="$(./run-tests 2>&1)";
success_rate="$(echo "$test_results" | tail -1)"
message="$user_message: $success_rate

$test_results"

echo "Commiting with message:"
echo "$message"
hg commit --addremove --message "$message"