#!/bin/bash

test_results="$(./run-tests 2>&1)";
success_rate="$(echo "$test_results" | tail -1)"
message="$success_rate

$test_results"

echo "Commiting with message:"
echo "$message"
hg commit --addremove --message "$message"